require 'rake'
require 'rubygems'

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
    test.libs << 'lib' << 'test'
    test.pattern = 'test/*.rb'
    test.verbose = true
  end

task :test => :check_dependencies

task :default => :test
